-- Expand enums to accept legacy (EN) and new (PT-BR) values during data conversion.
ALTER TABLE `Order`
  MODIFY `status` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDING',
  MODIFY `fulfillmentStatus` ENUM(
    'PENDING',
    'SEPARATING',
    'PACKED',
    'DISPATCHED',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'SEPARANDO',
    'EMBALADO',
    'DESPACHADO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `Payment`
  MODIFY `status` ENUM(
    'PENDING',
    'APPROVED',
    'REJECTED',
    'CANCELLED',
    'REFUNDED',
    'PENDENTE',
    'APROVADO',
    'RECUSADO',
    'CANCELADO',
    'REEMBOLSADO'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `OrderStatusHistory`
  MODIFY `fromStatus` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NULL,
  MODIFY `toStatus` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL;

-- Convert existing records from English values to PT-BR.
UPDATE `Order`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Order`
SET `fulfillmentStatus` = CASE `fulfillmentStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'SEPARATING' THEN 'SEPARANDO'
  WHEN 'PACKED' THEN 'EMBALADO'
  WHEN 'DISPATCHED' THEN 'DESPACHADO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `fulfillmentStatus`
END;

UPDATE `Payment`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'APPROVED' THEN 'APROVADO'
  WHEN 'REJECTED' THEN 'RECUSADO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  WHEN 'REFUNDED' THEN 'REEMBOLSADO'
  ELSE `status`
END;

UPDATE `OrderStatusHistory`
SET `fromStatus` = CASE `fromStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `fromStatus`
END;

UPDATE `OrderStatusHistory`
SET `toStatus` = CASE `toStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `toStatus`
END;

-- Lock enums to PT-BR values only.
ALTER TABLE `Order`
  MODIFY `status` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE',
  MODIFY `fulfillmentStatus` ENUM(
    'PENDENTE',
    'SEPARANDO',
    'EMBALADO',
    'DESPACHADO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Payment`
  MODIFY `status` ENUM('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO', 'REEMBOLSADO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `OrderStatusHistory`
  MODIFY `fromStatus` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NULL,
  MODIFY `toStatus` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NOT NULL;
