-- Expand enums to accept legacy (EN) and new (PT-BR) values during data conversion.
ALTER TABLE `User`
  MODIFY `status` ENUM(
    'ACTIVE',
    'INACTIVE',
    'SUSPENDED',
    'CANCELLED',
    'ATIVO',
    'INATIVO',
    'SUSPENSO',
    'CANCELADO'
  ) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `Appointment`
  MODIFY `status` ENUM(
    'PENDING',
    'CONFIRMED',
    'CANCELLED',
    'PENDENTE',
    'CONFIRMADO',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `Subscription`
  MODIFY `status` ENUM(
    'ACTIVE',
    'PENDING',
    'CANCELLED',
    'DELINQUENT',
    'ATIVA',
    'PENDENTE',
    'CANCELADA',
    'INADIMPLENTE'
  ) NOT NULL DEFAULT 'PENDING';

-- Convert existing records from English values to PT-BR.
UPDATE `User`
SET `status` = CASE `status`
  WHEN 'ACTIVE' THEN 'ATIVO'
  WHEN 'INACTIVE' THEN 'INATIVO'
  WHEN 'SUSPENDED' THEN 'SUSPENSO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Appointment`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'CONFIRMED' THEN 'CONFIRMADO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Subscription`
SET `status` = CASE `status`
  WHEN 'ACTIVE' THEN 'ATIVA'
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'CANCELLED' THEN 'CANCELADA'
  WHEN 'DELINQUENT' THEN 'INADIMPLENTE'
  ELSE `status`
END;

-- Lock enums to PT-BR values only.
ALTER TABLE `User`
  MODIFY `status` ENUM('ATIVO', 'INATIVO', 'SUSPENSO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `Appointment`
  MODIFY `status` ENUM('PENDENTE', 'CONFIRMADO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Subscription`
  MODIFY `status` ENUM('ATIVA', 'PENDENTE', 'CANCELADA', 'INADIMPLENTE') NOT NULL DEFAULT 'PENDENTE';
