-- Reassert PT-BR enums across environments where an older EN snapshot may still exist.

-- 1) Expand enum domains temporarily (EN + PT-BR) to allow safe data conversion.
ALTER TABLE `Order`
  MODIFY `status` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDENTE',
  MODIFY `fulfillmentStatus` ENUM(
    'PENDING',
    'SEPARATING',
    'PACKED',
    'DISPATCHED',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'SEPARANDO',
    'EMBALADO',
    'DESPACHADO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Payment`
  MODIFY `status` ENUM(
    'PENDING',
    'APPROVED',
    'REJECTED',
    'CANCELLED',
    'REFUNDED',
    'PENDENTE',
    'APROVADO',
    'RECUSADO',
    'CANCELADO',
    'REEMBOLSADO'
  ) NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `OrderStatusHistory`
  MODIFY `fromStatus` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NULL,
  MODIFY `toStatus` ENUM(
    'PENDING',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    'PENDENTE',
    'PAGO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL;

ALTER TABLE `User`
  MODIFY `status` ENUM(
    'ACTIVE',
    'INACTIVE',
    'SUSPENDED',
    'CANCELLED',
    'ATIVO',
    'INATIVO',
    'SUSPENSO',
    'CANCELADO'
  ) NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `Appointment`
  MODIFY `status` ENUM(
    'PENDING',
    'CONFIRMED',
    'CANCELLED',
    'PENDENTE',
    'CONFIRMADO',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Subscription`
  MODIFY `status` ENUM(
    'ACTIVE',
    'PENDING',
    'CANCELLED',
    'DELINQUENT',
    'ATIVA',
    'PENDENTE',
    'CANCELADA',
    'INADIMPLENTE'
  ) NOT NULL DEFAULT 'PENDENTE';

-- 2) Convert any residual EN values to PT-BR.
UPDATE `Order`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Order`
SET `fulfillmentStatus` = CASE `fulfillmentStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'SEPARATING' THEN 'SEPARANDO'
  WHEN 'PACKED' THEN 'EMBALADO'
  WHEN 'DISPATCHED' THEN 'DESPACHADO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `fulfillmentStatus`
END;

UPDATE `Payment`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'APPROVED' THEN 'APROVADO'
  WHEN 'REJECTED' THEN 'RECUSADO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  WHEN 'REFUNDED' THEN 'REEMBOLSADO'
  ELSE `status`
END;

UPDATE `OrderStatusHistory`
SET `fromStatus` = CASE `fromStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `fromStatus`
END;

UPDATE `OrderStatusHistory`
SET `toStatus` = CASE `toStatus`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'PAID' THEN 'PAGO'
  WHEN 'SHIPPED' THEN 'ENVIADO'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `toStatus`
END;

UPDATE `User`
SET `status` = CASE `status`
  WHEN 'ACTIVE' THEN 'ATIVO'
  WHEN 'INACTIVE' THEN 'INATIVO'
  WHEN 'SUSPENDED' THEN 'SUSPENSO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Appointment`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'CONFIRMED' THEN 'CONFIRMADO'
  WHEN 'CANCELLED' THEN 'CANCELADO'
  ELSE `status`
END;

UPDATE `Subscription`
SET `status` = CASE `status`
  WHEN 'ACTIVE' THEN 'ATIVA'
  WHEN 'PENDING' THEN 'PENDENTE'
  WHEN 'CANCELLED' THEN 'CANCELADA'
  WHEN 'DELINQUENT' THEN 'INADIMPLENTE'
  ELSE `status`
END;

-- 3) Lock enum domains to PT-BR only.
ALTER TABLE `Order`
  MODIFY `status` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE',
  MODIFY `fulfillmentStatus` ENUM(
    'PENDENTE',
    'SEPARANDO',
    'EMBALADO',
    'DESPACHADO',
    'ENVIADO',
    'ENTREGUE',
    'CANCELADO'
  ) NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Payment`
  MODIFY `status` ENUM('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO', 'REEMBOLSADO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `OrderStatusHistory`
  MODIFY `fromStatus` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NULL,
  MODIFY `toStatus` ENUM('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NOT NULL;

ALTER TABLE `User`
  MODIFY `status` ENUM('ATIVO', 'INATIVO', 'SUSPENSO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `Appointment`
  MODIFY `status` ENUM('PENDENTE', 'CONFIRMADO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `Subscription`
  MODIFY `status` ENUM('ATIVA', 'PENDENTE', 'CANCELADA', 'INADIMPLENTE') NOT NULL DEFAULT 'PENDENTE';
