-- AlterTable
ALTER TABLE `User`
  ADD COLUMN `phone2` VARCHAR(191) NULL,
  ADD COLUMN `city` VARCHAR(191) NULL,
  ADD COLUMN `neighborhood` VARCHAR(191) NULL,
  ADD COLUMN `avatarUrl` VARCHAR(191) NULL,
  ADD COLUMN `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN `emailVerified` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `rating` INTEGER NULL,
  ADD COLUMN `lastAccessAt` DATETIME(3) NULL,
  MODIFY `role` ENUM('MASTER', 'ADMIN', 'MANAGER', 'PROFESSIONAL', 'CLIENT') NOT NULL DEFAULT 'CLIENT';
